# Generated by Django 4.1.7 on 2023-03-30 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_alter_user_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='eventBooked',
            field=models.ManyToManyField(blank=True, to='event.event'),
        ),
    ]
