# Generated by Django 4.1.7 on 2023-04-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_alter_user_eventbooked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='./event/templates')),
                ('head', models.CharField(max_length=50)),
                ('para', models.CharField(max_length=100)),
            ],
        ),
    ]
